### PR TITLE
<img> hack to render 1st eqn in methods.md

### PR DESCRIPTION
**Pull request by ctwardy**
Just did one equation so you can see if you like it. 

Note you have to URLencode some symbols like "+" and ";". (Though here I just substituted ":" for ";".)

### CODE REVIEW

**Comment by zhengp0** [comment]
Thanks very much for the tips! Will try it out soon :)

**Comment by delgadom** [comment]
Thanks so much for posting this online and wading through the onslaught of attention on github on top of the vital work you are doing! Just a tip in case it's helpful - if you look at the "files changed" tab and then click on the "rich diff" you can preview the changes. they look good to me!

Screen Shot 2020-04-05 at 12 05 23 PM

**Comment by ctwardy** [comment]
@delgadom - Not sure if that comment was to me or @zhengp0 ?  

I had already previewed.  I just wasn't sure you wanted to take this approach generally, as it's github-centric.

**Comment by delgadom** [comment]
sorry that was a tip for @zhengp0. thanks for the fix @ctwardy :)

**Comment by zhengp0** [comment]
Thanks guys! @delgadom @ctwardy The `md` files are link to the website and should be view here https://ihmeuw-msca.github.io/CurveFit/

**Comment by ctwardy** [comment]
Aha. Then this might be a breaking change for that site. Too bad github.com doesn't render the same way.

**Comment by mbannick** [comment]
I think we'll keep our current docs with rendering on the GitHub pages rather than markdown to be safe, but thank you very much for the suggestion @ctwardy! If we switch to a different documentation rendering platform in the future we'll keep this in mind.

**Pull request closed without merging**
